### ISSUE TITLE
가게명이 길면 글자가 넘치는 이슈

### ISSUE THREAD

**Issue by MinGu-Jeong** [BCSDLab/KOIN_OWNER_WEB#101]
## Describe the bug
가게명이 길면 배달가능 글자가 넘치는 버그가 있습니다.

## Screenshot
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/dcc605fa-4996-4b21-b47b-50b426983016)

## Environment

**Desktop:**

**Smartphone:**

**Comment by ChoiWonBeen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[프론트엔드 - 코인] 트렐로 이슈생성 테스트](https://trello.com/c/tAqYuRsD/44-%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C-%EC%BD%94%EC%9D%B8-%ED%8A%B8%EB%A0%90%EB%A1%9C-%EC%9D%B4%EC%8A%88%EC%83%9D%EC%84%B1-%ED%85%8C%EC%8A%A4%ED%8A%B8)
