### ISSUE TITLE
[공통] 헤더 추가

### ISSUE THREAD

**Issue by kimeodml** [BCSDLab/KOIN_OWNER_WEB#4]
## Feature Name

공통의 상단바 구현
## Progress

- [x] 헤더 구현

## Design Screenshot
![image](https://user-images.githubusercontent.com/88065770/230897177-6ee6c6de-b2d3-4ad3-b589-db20599d35fa.png)
![image](https://user-images.githubusercontent.com/88065770/230896680-175006fc-0bbb-43c8-be5f-92f98f4d932b.png)

**Comment by ChoiWonBeen** [comment]
여기쪽은 RECODE에 디자인을 옮겨다 쓴 부분이 있을거라 매장관리 탭만 있으면 될거예요!
나머지 네비게이션은 따로 필요하지 않을 것 같네요

**Comment by kimeodml** [comment]
알겠습니다!
