### ISSUE TITLE
가게 정보 수정 기능 추가 필요

### ISSUE THREAD

**Issue by hoooooony** [BCSDLab/KOIN_OWNER_WEB#44]
## Describe the bug
가게정보 수정 눌러도 아무 반응 없음

## To Reproduce
1. Go to '내 가게 정보 화면'
2. Click on '가게 정보 수정 눌렀을때'
3. 아무런 동작이 없음

## Screenshot
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/112807899/04d7a85f-230d-4f43-b394-3c4e01e727f6)

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudekim** [comment]
@hoooooony  이거 아직 구현안된 기능이랑 다음 배포로 넘겨야할듯
