### ISSUE TITLE
상단 Nav바에서 정보 수정 클릭시 빈페이지 이동

### ISSUE THREAD

**Issue by hoooooony** [BCSDLab/KOIN_OWNER_WEB#49]
## Describe the bug
상단 Nav바에서 정보 수정 클릭시 빈페이지 이동

## Screenshot
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/112807899/da29d6e4-72fd-462d-8f54-c883a50d53f7)
## Environment

**Desktop:**

**Smartphone:**

**Comment by MinGu-Jeong** [comment]
#99 개발중 페이지로 이동하도록 수정했습니다
