### ISSUE TITLE
회원가입 모바일 뷰에서 중복되는 이메일 입력시에도 인증 화면으로 넘어가짐

### ISSUE THREAD

**Issue by HAEROOL** [BCSDLab/KOIN_OWNER_WEB#71]
## Describe the bug
모바일 뷰에서 중복되는 이메일 입력시, 중복되는 이메일 직전에 입력한 이메일 문자열을 사용하며 인증화면으로 넘어감
ex) asdf.abcde@.com이 중복이라면 asdf.abcde@.co를 사용하며 인증화면으로 넘어가짐

## Environment

**Desktop:**

**Smartphone:**

**Comment by hanagertrudekim** [comment]
이거 이메일 validate가 원래 없는건가요??

**Comment by HAEROOL** [comment]
모바일의 경우 중복체크를 클릭해서 하는 게 아니라 문자열이 변경될 때마다 체크를 하는 로직이 되다보니, 직전의 문자열이 적용되서 그런 것 같아요. ~~.com이 중복이면 ~~.co까지 입력 됐을때는 중복되지 않으니 이게 그대로 회원가입 데이터로 적용되어 버리는 것 같네요.
